services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    preDeployCommand: |
      sudo apt-get update && sudo apt-get install -y ffmpeg
